### ISSUE TITLE
Ошибка NPE при добавлении задачи

### ISSUE THREAD

**Issue by anry-das** [roman220303/pr1#10]
При попытке добавить задачу после ввода данных получаем **NullPointerException**. Это критическая ошибка (приложение не может функционировать с такой ошибкой), ее необходимо исправить.

**Comment by roman220303** [comment]
[d76f47c](https://github.com/roman220303/pr1/commit/d76f47ce89bf8c157358dbf2df2fc7480a0ecad0)
