### ISSUE TITLE
Перенести в View

### ISSUE THREAD

**Issue by anry-das** [roman220303/pr1#11]
Получение ввода от пользователя - задача View, а не Controller. Поэтому необходимо перенести `private String keyboardReadWholeLn()` в Представление.
Также обрати внимание, что в createTask() создается локальная переменная
Task model = new Task
а вызывается поле класса
this.model.setTitle(strTitle);

**Comment by roman220303** [comment]
[b154148](https://github.com/roman220303/pr1/commit/b154148942d69222e2e29d53c39c424b2528e0a0)

**Comment by roman220303** [comment]
[a146fac](https://github.com/roman220303/pr1/commit/a146fac064706179fb45dd97c318f8720c9583b7) - это
