### ISSUE TITLE
Доработать Контроллер и Представление

### ISSUE THREAD

**Issue by anry-das** [roman220303/pr1#12]
Задача Представления - получить данные (в экземпляр класса) и передать (вернуть) его на обработку в Контроллер, которой должен передать на сохранение этот экземпляр в Модель.
Сейчас все происходит совсем не так: данные вводятся в контроллере, Представление выводит ТОЛЬКО главное меню.
Необходимо изменить поведение частей приложения.
Также смотри #11

**Comment by roman220303** [comment]
[b154148](https://github.com/roman220303/pr1/commit/b154148942d69222e2e29d53c39c424b2528e0a0)

**Comment by anry-das** [comment]
Контроллер и Представление не достаточно разнесены
