### ISSUE TITLE
Правильный вывод ошибок

### ISSUE THREAD

**Issue by anry-das** [roman220303/pr1#14]
Для вывода сообщения при ошибке недостаточно использовать e.printStackTrace();. Необходимо также выводить тематическое сообщение и название ошибки. Также в данном случае лучше использовать логгер.
(см. #13 )

**Comment by roman220303** [comment]
[a4648a6](https://github.com/roman220303/pr1/commit/a4648a653cdbc4757b7effe078fcddd941e8c771)
