### ISSUE TITLE
Добавить исправить логирование

### ISSUE THREAD

**Issue by das13** [roman220303/pr1#24]
В ua.edu.sumdu.j2se.roman.tasks.controller.Controller#run нужно:
- добавить логгирование в `catch (NullPointerException e)` и в `catch (InterruptedException e)` (можно с заменой e.printStackTrace())
- `logger.info()` в секциях **catch** заменить на **ERROR**

**Comment by roman220303** [comment]
[3976ea1](https://github.com/roman220303/pr1/commit/3976ea1feec0a707a11d72d425d5eb5ca134e2c0)
