### ISSUE TITLE
Отлавливать отсутствие файла данных

### ISSUE THREAD

**Issue by anry-das** [roman220303/pr1#9]
При запуске программы, если отсутствует файл данных, то выдается сообщение об ошибке.
Необходимо сделать так, чтобы в таком случае создавался новый файл, а сообщение об ошибке не выводилось.

**Comment by roman220303** [comment]
[9f566e9](https://github.com/roman220303/pr1/commit/9f566e91e2b6db2eec58c298184811bf2c85d82a)
